photo_blogger_photo_homepage:
    path:     /
    defaults: { _controller: PhotoBloggerPhotoBundle:Default:index }

PhotoBloggerPhotoBundle_emailsend:
    pattern:  /cont
    defaults: { _controller: PhotoBloggerPhotoBundle:Default:emailSend }
    requirements:
        _method:  GET|POST